export const ab = {
  "resultList": [
    {
      "id": 15409,
      "name": "test-web-core",
      "description": "测试页面工具",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [65126, 65127],
      "cmdbSettings": "{\"isSpa\":true,\"serviceTypes\":\"static-web\",\"buildTool\":\"pnpm\",\"innerSite\":false,\"prdogParams\":{\"runEnv\":2,\"name\":\"test-web-core\",\"urlPrefixProd\":\"https://m.ximalaya.com\",\"urlPrefixTest\":\"https://m.test.ximalaya.com\"},\"spaConfig\":{\"activity\":0,\"applicationName\":\"test-web-core\",\"applicationIntro\":\"测试页面工具\",\"qps\":\"1\",\"pageSize\":\"1\",\"domainTest\":\"m.test.ximalaya.com\",\"domainPrd\":\"m.ximalaya.com\"},\"languageVersion\":\"16.14.0\",\"deployServer\":\"huaweicloud\",\"language\":\"Javascript\",\"imageName\":\"\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 0,
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 15406,
      "name": "risk-watcher",
      "description": "风控监控系统\n测试地址\nhttps://rc.test.ximaoa.com/gatekeeper/risk-watcher/goods-risk-control/goods",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [65119, 65120],
      "cmdbSettings": "{\"isSpa\":true,\"serviceTypes\":\"static-web\",\"buildTool\":\"pnpm\",\"innerSite\":false,\"prdogParams\":{\"runEnv\":2,\"name\":\"risk-watcher\",\"urlPrefixProd\":\"https://ops.ximalaya.com\",\"urlPrefixTest\":\"https://ops.test.ximalaya.com\"},\"spaConfig\":{\"activity\":0,\"applicationName\":\"risk-watcher\",\"applicationIntro\":\"风控监控系统\",\"qps\":\"1\",\"pageSize\":\"1\",\"domainTest\":\"ops.test.ximalaya.com\",\"domainPrd\":\"ops.ximalaya.com\"},\"languageVersion\":\"16.14.0\",\"deployServer\":\"huaweicloud\",\"language\":\"Javascript\",\"imageName\":\"\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 15394,
      "name": "web-auto-test",
      "description": "web页面自动测试",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [65094, 68084, 65093, 65095],
      "cmdbSettings": "{\"appType\":\"online\",\"buildTool\":\"yarn\",\"defaultMaxSurge\":100,\"httpPort\":12617,\"isStateful\":false,\"language\":\"Node\",\"languageVersion\":\"16.14.0\",\"minReady\":120,\"namespace\":\"dszt-pay\",\"namespaceDesc\":\"支付平台@电商中台\",\"observation\":false,\"packageType\":31,\"serviceTypes\":\"node\",\"silent\":false,\"webPort\":8080}",
      "serviceTypes": "node",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 0,
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 15141,
      "name": "pay-ops",
      "description": "支付运营台\n\nhttps://ops.test.ximalaya.com/gatekeeper/pay-ops",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [64600, 64601],
      "cmdbSettings": "{\"isSpa\":true,\"serviceTypes\":\"static-web\",\"buildTool\":\"pnpm\",\"innerSite\":false,\"prdogParams\":{\"runEnv\":2,\"name\":\"pay-ops\",\"urlPrefixProd\":\"https://ops.ximalaya.com\",\"urlPrefixTest\":\"https://ops.test.ximalaya.com\"},\"spaConfig\":{\"activity\":0,\"applicationName\":\"pay-ops\",\"applicationIntro\":\"支付运营台\",\"qps\":\"1\",\"pageSize\":\"1\",\"domainTest\":\"ops.test.ximalaya.com\",\"domainPrd\":\"ops.ximalaya.com\"},\"languageVersion\":\"16.14.0\",\"deployServer\":\"huaweicloud\",\"language\":\"Javascript\",\"imageName\":\"\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 15076,
      "name": "pay-promotion-manage",
      "description": "支付营销管理 营销中心子应用 promotion-manage\n\nhttps://ops.test.ximalaya.com/gatekeeper/pay-promotion-manage",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [64446, 64447],
      "cmdbSettings": "{\"isSpa\":true,\"serviceTypes\":\"static-web\",\"buildTool\":\"pnpm\",\"innerSite\":false,\"prdogParams\":{\"runEnv\":2,\"name\":\"pay-promotion-manage\",\"urlPrefixProd\":\"https://ops.ximalaya.com\",\"urlPrefixTest\":\"https://ops.test.ximalaya.com\"},\"spaConfig\":{\"activity\":0,\"applicationName\":\"pay-promotion-manage\",\"applicationIntro\":\"支付营销管理 营销中心子应用 promotion-manage\",\"qps\":\"1\",\"pageSize\":\"1\",\"domainTest\":\"ops.test.ximalaya.com\",\"domainPrd\":\"ops.ximalaya.com\"},\"languageVersion\":\"16.14.0\",\"deployServer\":\"huaweicloud\",\"language\":\"Javascript\",\"imageName\":\"\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 14281,
      "name": "handler-center-checkstand",
      "description": "引导跳转h5收银台支付\n\nhttps://m.test.ximalaya.com/gatekeeper/handler-center-checkstand/submit-checkstand-form?tradeOrderNo=",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [58792, 58793],
      "cmdbSettings": "{\"isSpa\":true,\"serviceTypes\":\"static-web\",\"buildTool\":\"pnpm\",\"innerSite\":false,\"prdogParams\":{\"runEnv\":1,\"name\":\"handler-center-checkstand\",\"urlPrefixProd\":\"https://m.ximalaya.com\",\"urlPrefixTest\":\"https://m.test.ximalaya.com\"},\"spaConfig\":{\"activity\":0,\"applicationName\":\"handler-center-checkstand\",\"applicationIntro\":\"引导跳转h5收银台支付\",\"qps\":\"1\",\"pageSize\":\"1\",\"domainTest\":\"m.test.ximalaya.com\",\"domainPrd\":\"m.ximalaya.com\"},\"languageVersion\":\"16.14.0\",\"deployServer\":\"production\",\"language\":\"Javascript\",\"imageName\":\"\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 14120,
      "name": "call-xima-app",
      "description": "唤起喜马app",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [58448, 58449],
      "cmdbSettings": "{\"isSpa\":true,\"serviceTypes\":\"static-web\",\"buildTool\":\"pnpm\",\"innerSite\":false,\"prdogParams\":{\"runEnv\":1,\"name\":\"call-xima-app\",\"urlPrefixProd\":\"https://m.ximalaya.com\",\"urlPrefixTest\":\"https://m.test.ximalaya.com\"},\"spaConfig\":{\"activity\":0,\"applicationName\":\"call-xima-app\",\"applicationIntro\":\"唤起喜马app\",\"qps\":\"1\",\"pageSize\":\"1\",\"domainTest\":\"m.test.ximalaya.com\",\"domainPrd\":\"m.ximalaya.com\"},\"languageVersion\":\"16.14.0\",\"deployServer\":\"production\",\"language\":\"Javascript\",\"imageName\":\"\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 0,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 14045,
      "name": "wechat-admin-platform",
      "description": "微信公众号平台管理",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [58202, 58203],
      "cmdbSettings": "{\"isSpa\":true,\"serviceTypes\":\"static-web\",\"buildTool\":\"pnpm\",\"innerSite\":false,\"prdogParams\":{\"runEnv\":2,\"name\":\"wechat-admin-platform\",\"urlPrefixProd\":\"https://ops.ximalaya.com\",\"urlPrefixTest\":\"https://ops.test.ximalaya.com\"},\"spaConfig\":{\"activity\":0,\"applicationName\":\"wechat-admin-platform\",\"applicationIntro\":\"微信公众号平台管理\",\"qps\":\"1\",\"pageSize\":\"1\",\"domainTest\":\"ops.test.ximalaya.com\",\"domainPrd\":\"ops.ximalaya.com\"},\"languageVersion\":\"16.14.0\",\"deployServer\":\"production\",\"language\":\"Javascript\",\"imageName\":\"\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 0,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 13935,
      "name": "budget-system-out",
      "description": "财务中台对外项目地址 /** 分割线 **/ /** 分割线 **/\n/** 分割线 **/ /** 分割线 **/\n\nhttp://ops.test.ximalaya.com/gatekeeper/budget-system-out/iframe-confirm-payment\n\n/** 分割线 **/ /** 分割线 **/\n/** 分割线 **/ /** 分割线 **/\n/** 分割线 **/ /** 分割线 **/\n\n\nhttp://ops.test.ximalaya.com/gatekeeper/budget-system-out/online-bank",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [58007, 58008],
      "cmdbSettings": "{\"isSpa\":true,\"serviceTypes\":\"static-web\",\"buildTool\":\"pnpm\",\"innerSite\":false,\"prdogParams\":{\"runEnv\":2,\"name\":\"budget-system-out\",\"urlPrefixProd\":\"https://ops.ximalaya.com\",\"urlPrefixTest\":\"https://ops.test.ximalaya.com\"},\"spaConfig\":{\"activity\":0,\"applicationName\":\"budget-system-out\",\"applicationIntro\":\"财务中台对外项目地址\",\"qps\":\"1\",\"pageSize\":\"1\",\"domainTest\":\"ops.test.ximalaya.com\",\"domainPrd\":\"ops.ximalaya.com\"},\"languageVersion\":\"16.14.0\",\"deployServer\":\"production\",\"language\":\"Javascript\",\"imageName\":\"\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 13911,
      "name": "guide-wx-fllow",
      "description": "引导关注微信公众号\n\nhttps://m.test.ximalaya.com/gatekeeper/guide-wx-fllow/qr-code\n",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [57962, 57963],
      "cmdbSettings": "{\"isSpa\":true,\"serviceTypes\":\"static-web\",\"buildTool\":\"pnpm\",\"innerSite\":false,\"prdogParams\":{\"runEnv\":1,\"name\":\"guide-wx-fllow\",\"urlPrefixProd\":\"https://m.ximalaya.com\",\"urlPrefixTest\":\"https://m.test.ximalaya.com\"},\"spaConfig\":{\"activity\":0,\"applicationName\":\"guide-wx-fllow\",\"applicationIntro\":\"引导关注微信公众号\",\"qps\":\"1\",\"pageSize\":\"1\",\"domainTest\":\"m.test.ximalaya.com\",\"domainPrd\":\"m.ximalaya.com\"},\"languageVersion\":\"16.14.0\",\"deployServer\":\"production\",\"language\":\"Javascript\",\"imageName\":\"\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 13907,
      "name": "continuous-subscribe-checkstand",
      "description": "连续订阅h5收银台 站外\n\nhttps://m.test.ximalaya.com/gatekeeper/continuous-subscribe-checkstand/checkstand?itemId=1&source=2&returnUrl=3",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [57951, 57952],
      "cmdbSettings": "{\"isSpa\":true,\"serviceTypes\":\"static-web\",\"buildTool\":\"pnpm\",\"innerSite\":false,\"prdogParams\":{\"runEnv\":1,\"name\":\"continuous-subscribe-checkstand\",\"urlPrefixProd\":\"https://m.ximalaya.com\",\"urlPrefixTest\":\"https://m.test.ximalaya.com\"},\"spaConfig\":{\"activity\":0,\"applicationName\":\"continuous-subscribe-checkstand\",\"applicationIntro\":\"连续订阅h5收银台 站外\",\"qps\":\"1\",\"pageSize\":\"1\",\"domainTest\":\"m.test.ximalaya.com\",\"domainPrd\":\"m.ximalaya.com\"},\"languageVersion\":\"16.14.0\",\"deployServer\":\"production\",\"language\":\"Javascript\",\"imageName\":\"\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 13897,
      "name": "business-scrm-weixin-web",
      "description": "微信生态-WEB端接口服务（外网）",
      "gitExistProject": false,
      "ownerName": "秦宇",
      "pipelineIds": [57935, 67646, 61745],
      "cmdbSettings": "{\"appType\":\"online\",\"buId\":2,\"buildTool\":\"maven\",\"defaultMaxSurge\":100,\"deployServer\":\"production\",\"healthCheckType\":1,\"imageName\":\"\",\"isStateful\":false,\"language\":\"Java\",\"languageVersion\":\"jdk8\",\"minReady\":120,\"namespace\":\"dszt-platform\",\"namespaceDesc\":\"电商平台@电商中台\",\"observation\":false,\"packageType\":1,\"projectLevel\":\"135\",\"serviceTypes\":\"web\",\"silent\":false}",
      "serviceTypes": "web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 0,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 13661,
      "name": "business-scrm-dashboard",
      "description": "scrm前端应用",
      "gitExistProject": false,
      "ownerName": "吴让好",
      "pipelineIds": [57514, 57515],
      "cmdbSettings": "{\"isSpa\":true,\"serviceTypes\":\"static-web\",\"buildTool\":\"yarn\",\"innerSite\":false,\"prdogParams\":{\"runEnv\":2,\"name\":\"business-scrm-dashboard\",\"urlPrefixProd\":\"https://ops.ximalaya.com\",\"urlPrefixTest\":\"https://ops.test.ximalaya.com\"},\"spaConfig\":{\"activity\":0,\"applicationName\":\"business-scrm-dashboard\",\"applicationIntro\":\"scrm前端应用\",\"domainTest\":\"ops.test.ximalaya.com\",\"domainPrd\":\"ops.ximalaya.com\",\"qps\":\"1\",\"pageSize\":\"1\"},\"languageVersion\":\"16.14.0\",\"deployServer\":\"production\",\"language\":\"Javascript\",\"imageName\":\"\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 0,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 13586,
      "name": "aigc-video-compositing-preview",
      "description": "AIGC视频合成 预览",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [57389, 57390],
      "cmdbSettings": "{\"isSpa\":true,\"serviceTypes\":\"static-web\",\"buildTool\":\"pnpm\",\"innerSite\":false,\"prdogParams\":{\"runEnv\":2,\"name\":\"aigc-video-compositing-preview\",\"urlPrefixProd\":\"https://ops.ximalaya.com\",\"urlPrefixTest\":\"https://ops.test.ximalaya.com\"},\"spaConfig\":{\"activity\":0,\"applicationName\":\"aigc-video-compositing-preview\",\"applicationIntro\":\"AIGC视频合成 预览\",\"domainTest\":\"ops.test.ximalaya.com\",\"domainPrd\":\"ops.ximalaya.com\",\"qps\":\"1\",\"pageSize\":\"1\"},\"languageVersion\":\"16.14.0\",\"deployServer\":\"production\",\"language\":\"Javascript\",\"imageName\":\"\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 0,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 13585,
      "name": "aigc-video-compositing",
      "description": "AIGC视频合成\n\nhttps://ops.test.ximalaya.com/gatekeeper/aigc-video-compositing",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [57387, 57388],
      "cmdbSettings": "{\"isSpa\":true,\"serviceTypes\":\"static-web\",\"buildTool\":\"pnpm\",\"innerSite\":false,\"prdogParams\":{\"runEnv\":2,\"name\":\"aigc-video-compositing\",\"urlPrefixProd\":\"https://ops.ximalaya.com\",\"urlPrefixTest\":\"https://ops.test.ximalaya.com\"},\"spaConfig\":{\"activity\":0,\"applicationName\":\"aigc-video-compositing\",\"applicationIntro\":\"AIGC视频合成\",\"domainTest\":\"ops.test.ximalaya.com\",\"domainPrd\":\"ops.ximalaya.com\",\"qps\":\"1\",\"pageSize\":\"1\"},\"languageVersion\":\"16.14.0\",\"deployServer\":\"production\",\"language\":\"Javascript\",\"imageName\":\"\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 13478,
      "name": "bizfinancial-info-admin",
      "description": "业财transform-accounting-voucher子应用 财务详情\n\nhttp://ops.test.ximalaya.com/gatekeeper/bizfinancial-info-admin/financialbudget/indexCenter",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [57214, 57215],
      "cmdbSettings": "{\"isSpa\":true,\"serviceTypes\":\"static-web\",\"buildTool\":\"pnpm\",\"innerSite\":false,\"prdogParams\":{\"runEnv\":2,\"name\":\"bizfinancial-info-admin\",\"urlPrefixProd\":\"https://ops.ximalaya.com\",\"urlPrefixTest\":\"https://ops.test.ximalaya.com\"},\"spaConfig\":{\"activity\":0,\"applicationName\":\"bizfinancial-info-admin\",\"applicationIntro\":\"业财transform-accounting-voucher子应用 财务详情\",\"domainTest\":\"ops.test.ximalaya.com\",\"domainPrd\":\"ops.ximalaya.com\",\"qps\":\"1\",\"pageSize\":\"1\"},\"languageVersion\":\"16.14.0\",\"deployServer\":\"production\",\"language\":\"Javascript\",\"imageName\":\"\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 13221,
      "name": "intelligent-shopping-guide",
      "description": "智能导购H5\n\nhttps://m.test.ximalaya.com/gatekeeper/intelligent-shopping-guide?keywords=%E8%80%B3%E6%9C%BA&guideMode=MATERIAL&_fix_keyboard=1",
      "gitExistProject": false,
      "ownerName": "秦宇",
      "pipelineIds": [56816, 56817],
      "cmdbSettings": "{\"isSpa\":true,\"serviceTypes\":\"static-web\",\"buildTool\":\"yarn\",\"innerSite\":true,\"prdogParams\":{\"runEnv\":1,\"name\":\"intelligent-shopping-guide\",\"urlPrefixProd\":\"https://m.ximalaya.com\",\"urlPrefixTest\":\"https://m.test.ximalaya.com\"},\"spaConfig\":{\"activity\":0,\"applicationName\":\"intelligent-shopping-guide\",\"applicationIntro\":\"智能导购H5\",\"domainTest\":\"m.test.ximalaya.com\",\"domainPrd\":\"m.ximalaya.com\",\"qps\":\"20\",\"pageSize\":\"20\"},\"languageVersion\":\"16.14.0\",\"deployServer\":\"production\",\"language\":\"Javascript\",\"imageName\":\"\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 13055,
      "name": "checkstand-tools",
      "description": "前置收银台组件文档\n\nhttps://m.test.ximalaya.com/gatekeeper/checkstand-tools#/",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [56537, 56538],
      "cmdbSettings": "{\"isSpa\":true,\"serviceTypes\":\"static-web\",\"buildTool\":\"pnpm\",\"innerSite\":false,\"prdogParams\":{\"runEnv\":2,\"name\":\"checkstand-tools\",\"urlPrefixProd\":\"https://m.ximalaya.com\",\"urlPrefixTest\":\"https://m.test.ximalaya.com\"},\"spaConfig\":{\"activity\":0,\"applicationName\":\"checkstand-tools\",\"applicationIntro\":\"收银台组件文档\",\"domainTest\":\"m.test.ximalaya.com\",\"domainPrd\":\"m.ximalaya.com\",\"qps\":\"1\",\"pageSize\":\"1\"},\"languageVersion\":\"16.14.0\",\"deployServer\":\"production\",\"language\":\"Javascript\",\"imageName\":\"\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 12603,
      "name": "budget-manage",
      "description": "营销预算管理系统\nhttps://ops.test.ximalaya.com/gatekeeper/budget-manage/accountManagement/operation",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [55780, 55781],
      "cmdbSettings": "{\"buildTool\":\"pnpm\",\"innerSite\":false,\"language\":\"Javascript\",\"languageVersion\":\"16.14.0\",\"serviceTypes\":\"static-web\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 11497,
      "name": "xmly-s-low-code-render",
      "description": "mf 预览",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [52719, 52721],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"imageName\": \"\", \"innerSite\": false, \"observation\": false, \"prdogParams\": {\"name\": \"xmly-s-low-code-render\", \"runEnv\": 1, \"urlPrefixProd\": \"http://m.ximalaya.com/\", \"urlPrefixTest\": \"http://m.test.ximalaya.com/\"}, \"serviceTypes\": \"static-web\", \"languageVersion\": \"16.14.0\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 0,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 11496,
      "name": "xmly-s-low-code-control",
      "description": "mf 控制后台 http://m.test.ximalaya.com/gatekeeper/xmly-s-low-code-control",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [52716, 52718],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"imageName\": \"\", \"innerSite\": false, \"observation\": false, \"prdogParams\": {\"name\": \"xmly-s-low-code-control\", \"runEnv\": 1, \"urlPrefixProd\": \"http://m.ximalaya.com/\", \"urlPrefixTest\": \"http://m.test.ximalaya.com/\"}, \"serviceTypes\": \"static-web\", \"languageVersion\": \"16.14.0\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 11495,
      "name": "xmly-s-low-code-components",
      "description": "mf 组件",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [52713, 52715],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"innerSite\": false, \"observation\": false, \"serviceTypes\": \"static-web\", \"languageVersion\": \"16.13.0\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 11442,
      "name": "micro-salary-settle",
      "description": "主播工资结算线上化\n微前端 访问请到结算运营台",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [52540, 52542],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"imageName\": \"\", \"innerSite\": false, \"observation\": false, \"prdogParams\": {\"name\": \"micro-salary-settle\", \"runEnv\": 2, \"urlPrefixProd\": \"http://ops.ximalaya.com/\", \"urlPrefixTest\": \"http://ops.test.ximalaya.com/\"}, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"languageVersion\": \"14.15.0\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 11305,
      "name": "micro-taro",
      "description": "微前端-taro",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [52097, 52098, 52099],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"innerSite\": false, \"observation\": false, \"serviceTypes\": \"static-web\", \"languageVersion\": \"16.13.0\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 0,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 10904,
      "name": "psm-static",
      "description": "采用管理系统",
      "gitExistProject": false,
      "ownerName": "庞克臣",
      "pipelineIds": [50368, 50369, 50370],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"imageName\": \"\", \"innerSite\": false, \"observation\": false, \"prdogParams\": {\"name\": \"psm-static\", \"runEnv\": 2, \"urlPrefixProd\": \"https://ops.ximalaya.com\", \"urlPrefixTest\": \"https://ops.test.ximalaya.com\"}, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"languageVersion\": \"14.15.0\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 0,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 10861,
      "name": "fund-auth",
      "description": "资金认证前端子应用 本地启动请使用 yarn start:external",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [50164, 50165, 50166],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"imageName\": \"\", \"innerSite\": false, \"observation\": false, \"prdogParams\": {\"name\": \"fund-auth\", \"runEnv\": 2, \"urlPrefixProd\": \"http://ops.ximalaya.com/\", \"urlPrefixTest\": \"http://ops.test.ximalaya.com/\"}, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"languageVersion\": \"14.15.0\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 10815,
      "name": "supplier-manage",
      "description": "供应商管理系统 http://m.test.ximalaya.com/gatekeeper/supplier-manage/goods/list",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [49970, 49971, 49972],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"imageName\": \"\", \"innerSite\": false, \"observation\": false, \"prdogParams\": {\"name\": \"supplier-manage\", \"runEnv\": 2, \"urlPrefixProd\": \"https://m.ximalaya.com\", \"urlPrefixTest\": \"https://m.test.ximalaya.com\"}, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"languageVersion\": \"14.15.0\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 10800,
      "name": "crm-admin",
      "description": "营销中心 CRM 前端项目\n\nhttps://ops.test.ximalaya.com/ad-home/sales/customerManage/saleCustomer",
      "gitExistProject": false,
      "ownerName": "程玉兵",
      "pipelineIds": [49904, 49905, 49906],
      "cmdbSettings": "{\"buildTool\":\"yarn\",\"innerSite\":false,\"language\":\"Javascript\",\"languageVersion\":\"14.15.0\",\"serviceTypes\":\"static-web\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 10736,
      "name": "invoice-h5-new",
      "description": "新开票h5\nhttps://m.test.ximalaya.com/gatekeeper/invoice-h5-new",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [49614, 49615, 49616],
      "cmdbSettings": "{\"buildTool\":\"yarn\",\"innerSite\":true,\"language\":\"Javascript\",\"languageVersion\":\"16.14.0\",\"serviceTypes\":\"static-web\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 10695,
      "name": "faqs-list",
      "description": "常见问题列表H5 http://m.test.ximalaya.com/gatekeeper/faqs-list",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [49422, 49423, 49424],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"imageName\": \"\", \"innerSite\": true, \"observation\": false, \"prdogParams\": {\"name\": \"faqs-list\", \"runEnv\": 1, \"urlPrefixProd\": \"https://m.ximalaya.com\", \"urlPrefixTest\": \"https://m.test.ximalaya.com\"}, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"languageVersion\": \"14.15.0\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 10598,
      "name": "business-check-platform-admin",
      "description": "业务校验平台\nhttps://ops.test.ximalaya.com/gatekeeper/business-check-platform-admin",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [48965, 48966, 48967],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"imageName\": \"\", \"innerSite\": false, \"observation\": false, \"prdogParams\": {\"name\": \"business-check-platform-admin\", \"runEnv\": 2, \"urlPrefixProd\": \"http://ops.ximalaya.com/\", \"urlPrefixTest\": \"http://ops.test.ximalaya.com/\"}, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"languageVersion\": \"14.15.0\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 10453,
      "name": "fork-business-vip-presale-new",
      "description": "fork 主 app - 会员商品页（新改版页面）\nhttps://m.test.ximalaya.com/gatekeeper/fork-business-vip-presale-new",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [48310, 48312],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"imageName\": \"\", \"innerSite\": true, \"observation\": false, \"prdogParams\": {\"name\": \"fork-business-vip-presale-new\", \"runEnv\": 1, \"urlPrefixProd\": \"https://m.ximalaya.com\", \"urlPrefixTest\": \"https://m.test.ximalaya.com\"}, \"serviceTypes\": \"static-web\", \"languageVersion\": \"14.15.0\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 10449,
      "name": "verify-platform-income",
      "description": "资金认证H5 https://m.test.ximalaya.com/trade-verify/h5_index/capital/capital/33",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [48294, 48295, 48296],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"imageName\": \"\", \"isStateful\": false, \"observation\": false, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"languageVersion\": \"8.11.1\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 10426,
      "name": "ops-anchor-auth-capital",
      "description": "资金认证ops  http://ops.test.ximalaya.com/trade-verify/ops_index/capital",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [48198, 48199, 48200],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"imageName\": \"\", \"innerSite\": false, \"observation\": false, \"prdogParams\": {\"name\": \"ops-anchor-auth-capital\", \"runEnv\": 2, \"urlPrefixProd\": \"https://ops.ximalaya.com\", \"urlPrefixTest\": \"https://ops.test.ximalaya.com\"}, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"languageVersion\": \"14.15.0\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 10299,
      "name": "trade-order-manage-new",
      "description": "新交易管理后台(前后端分离) https://ops.test.ximalaya.com/gatekeeper/trade-order-manage-new/trade/tradeManage",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [47616, 47871],
      "cmdbSettings": "{\"buildTool\":\"yarn\",\"innerSite\":false,\"language\":\"Javascript\",\"languageVersion\":\"16.14.0\",\"serviceTypes\":\"static-web\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 10257,
      "name": "invoice-admin-new",
      "description": "新发票配置后台\nhttp://ops.test.ximalaya.com/gatekeeper/invoice-admin-new/invoice/setting",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [47432, 47434],
      "cmdbSettings": "{\"buildTool\":\"pnpm\",\"innerSite\":false,\"language\":\"Javascript\",\"languageVersion\":\"16.14.0\",\"serviceTypes\":\"static-web\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 10151,
      "name": "price-management-new",
      "description": "价格管理 前后端分离\nhttps://ops.test.ximalaya.com/gatekeeper/price-management-new#/price",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [46974, 46976],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"imageName\": \"\", \"innerSite\": false, \"observation\": false, \"prdogParams\": {\"name\": \"price-management-new\", \"runEnv\": 1, \"urlPrefixProd\": \"http://ops.ximalaya.com/\", \"urlPrefixTest\": \"http://ops.test.ximalaya.com/\"}, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"languageVersion\": \"14.15.0\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 10150,
      "name": "goods-item-management-new",
      "description": "商品管理后台https://ops.test.ximalaya.com/gatekeeper/goods-item-management-new#/item",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [46970, 46971, 46972],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"imageName\": \"\", \"innerSite\": false, \"observation\": false, \"prdogParams\": {\"name\": \"goods-item-management-new\", \"runEnv\": 1, \"urlPrefixProd\": \"http://ops.ximalaya.com/\", \"urlPrefixTest\": \"http://ops.test.ximalaya.com/\"}, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"languageVersion\": \"14.15.0\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 10149,
      "name": "goods-management-new",
      "description": "商品元数据后台\n新地址\nhttps://product.test.ximaoa.com/gatekeeper/goods-management-new#/\n\n老地址\nhttps://ops.test.ximalaya.com/gatekeeper/goods-management-new#/",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [46964, 46965, 46966],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"imageName\": \"\", \"innerSite\": false, \"observation\": false, \"prdogParams\": {\"name\": \"goods-management-new\", \"runEnv\": 1, \"urlPrefixProd\": \"https://ops.ximalaya.com\", \"urlPrefixTest\": \"https://ops.test.ximalaya.com\"}, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"languageVersion\": \"14.15.0\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 10072,
      "name": "center-handler-page",
      "description": "统一中间页处理仓库",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [46447, 46449],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"imageName\": \"\", \"innerSite\": true, \"observation\": false, \"prdogParams\": {\"name\": \"center-handler-page\", \"runEnv\": 1, \"urlPrefixProd\": \"https://m.ximalaya.com\", \"urlPrefixTest\": \"https://m.test.ximalaya.com\"}, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"languageVersion\": \"14.15.0\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 0,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 10013,
      "name": "retrieve-orderno",
      "description": "苹果找单功能h5\n\nhttps://m.test.ximalaya.com/gatekeeper/retrieve-orderno",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [46180, 46181, 46182],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"imageName\": \"\", \"innerSite\": true, \"observation\": false, \"prdogParams\": {\"name\": \"retrieve-orderno\", \"runEnv\": 1, \"urlPrefixProd\": \"https://m.ximalaya.com\", \"urlPrefixTest\": \"https://m.test.ximalaya.com\"}, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"languageVersion\": \"14.15.0\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 9766,
      "name": "shop-management-docs",
      "description": "商家中心 sop 文档",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [44993, 44994, 44995],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"imageName\": \"\", \"innerSite\": false, \"observation\": false, \"prdogParams\": {\"name\": \"shop-management-docs\", \"runEnv\": 2, \"urlPrefixProd\": \"https://m.ximalaya.com\", \"urlPrefixTest\": \"https://m.test.ximalaya.com\"}, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"languageVersion\": \"14.15.0\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 0,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 9721,
      "name": "caculation-micro",
      "description": "个税配置化 微前端 子应用",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [44782, 44783, 44784],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"innerSite\": false, \"observation\": false, \"serviceTypes\": \"static-web\", \"languageVersion\": \"14.15.0\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 0,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 9670,
      "name": "hybrid-cdkeys-new",
      "description": "新兑换码 h5\nhttp://m.test.ximalaya.com/gatekeeper/hybrid-cdkeys-new",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [44498, 44499, 44500],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"innerSite\": true, \"observation\": false, \"serviceTypes\": \"static-web\", \"languageVersion\": \"14.15.0\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 9668,
      "name": "my-glasses-customized",
      "description": "anker眼镜定制页面",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [44492, 44493, 44494],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"imageName\": \"\", \"innerSite\": false, \"observation\": false, \"prdogParams\": {\"name\": \"my-glasses-customized\", \"runEnv\": 1, \"urlPrefixProd\": \"http://m.ximalaya.com\", \"urlPrefixTest\": \"http://m.test.ximalaya.com\"}, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"languageVersion\": \"14.15.0\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 0,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 9381,
      "name": "piece-service",
      "description": "通用商品凑单页 http://m.test.ximalaya.com/gatekeeper/piece-service",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [43163, 43164, 43165],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"imageName\": \"\", \"innerSite\": false, \"observation\": false, \"prdogParams\": {\"name\": \"piece-service\", \"runEnv\": 1, \"urlPrefixProd\": \"https://m.ximalaya.com\", \"urlPrefixTest\": \"https://m.test.ximalaya.com\"}, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"languageVersion\": \"12.19.0\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 9371,
      "name": "business-gateway-open-doc",
      "description": "商业化接入平台文档",
      "gitExistProject": false,
      "ownerName": "于骁丹",
      "pipelineIds": [43083, 43084, 43085],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"npm\", \"imageName\": \"\", \"innerSite\": false, \"observation\": false, \"prdogParams\": {\"name\": \"business-gateway-open-doc\", \"runEnv\": 1, \"urlPrefixProd\": \"http://business.ximalaya.com\", \"urlPrefixTest\": \"http://business.test.ximalaya.com\"}, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"languageVersion\": \"10.16.2\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 0,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 9365,
      "name": "channel-receiving-system",
      "description": "全渠道收单系统",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [43015, 43016, 43017],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"imageName\": \"\", \"innerSite\": false, \"observation\": false, \"prdogParams\": {\"name\": \"channel-receiving-system\", \"runEnv\": 2, \"urlPrefixProd\": \"https://ops.ximalaya.com\", \"urlPrefixTest\": \"https://ops.test.ximalaya.com\"}, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"languageVersion\": \"12.19.0\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 0,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 9309,
      "name": "comprehensive-query",
      "description": "结算运营台qiankun子应用 综合查询功能",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [42698, 42699, 42700],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"imageName\": \"\", \"innerSite\": false, \"observation\": false, \"prdogParams\": {\"name\": \"comprehensive-query\", \"runEnv\": 2, \"urlPrefixProd\": \"http://ops.ximalaya.com/\", \"urlPrefixTest\": \"http://ops.test.ximalaya.com/\"}, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"languageVersion\": \"14.15.0\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 0,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 9280,
      "name": "business-vip-presale-new",
      "description": "主 app - 会员商品页（新改版页面）",
      "gitExistProject": false,
      "ownerName": "钱进",
      "pipelineIds": [42538, 42539, 42540],
      "cmdbSettings": "{\"buildTool\":\"yarn\",\"innerSite\":true,\"language\":\"Javascript\",\"languageVersion\":\"16.14.0\",\"serviceTypes\":\"static-web\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 0,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 9227,
      "name": "supply-chain-manage",
      "description": "供应链\nhttp://m.test.ximalaya.com/gatekeeper/supply-chain-manage/channel/shop",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [41029, 41031],
      "cmdbSettings": "{\"buildTool\":\"yarn\",\"innerSite\":false,\"language\":\"Javascript\",\"languageVersion\":\"16.14.0\",\"serviceTypes\":\"static-web\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 9188,
      "name": "presale-resource-allocation",
      "description": "实物售前页资源配置\nhttps://ops.test.ximalaya.com/gatekeeper/presale-resource-allocation#/position",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [40770, 40771, 40772],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"imageName\": \"\", \"innerSite\": false, \"observation\": false, \"prdogParams\": {\"name\": \"presale-resource-allocation\", \"runEnv\": 2, \"urlPrefixProd\": \"https://ops.ximalaya.com\", \"urlPrefixTest\": \"https://ops.test.ximalaya.com\"}, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"languageVersion\": \"12.19.0\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 9177,
      "name": "tcc-transaction-web-new",
      "description": "克隆一份新的 tcc-transaction-web 接口地址也有改变",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [40696, 40698, 40697],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"imageName\": \"\", \"innerSite\": false, \"observation\": false, \"prdogParams\": {\"name\": \"tcc-transaction-web-new\", \"runEnv\": 1, \"urlPrefixProd\": \"http://ops.ximalaya.com/\", \"urlPrefixTest\": \"http://ops.test.ximalaya.com/\"}, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"languageVersion\": \"14.15.0\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 0,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 9141,
      "name": "after-sale-service",
      "description": "售后页",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [40258, 40259, 40260],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"innerSite\": true, \"observation\": false, \"serviceTypes\": \"static-web\", \"languageVersion\": \"14.15.0\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 0,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 9080,
      "name": "balance-service-manage",
      "description": "虚拟余额管控 qiankun子应用",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [39762, 39763, 39764],
      "cmdbSettings": "{\"buildTool\":\"yarn\",\"innerSite\":false,\"language\":\"Javascript\",\"languageVersion\":\"16.14.0\",\"serviceTypes\":\"static-web\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 0,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 8900,
      "name": "settlement-clase",
      "description": "结算条款管理",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [35859, 35860, 35861],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"imageName\": \"\", \"innerSite\": false, \"isStateful\": false, \"observation\": false, \"prdogParams\": {\"name\": \"settlement-clase\", \"runEnv\": 2, \"urlPrefixProd\": \"http://ops.ximalaya.com/\", \"urlPrefixTest\": \"http://ops.test.ximalaya.com/\"}, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"languageVersion\": \"14.15.0\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 0,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 8763,
      "name": "payment-order-manage",
      "description": "付款单管理系统 qiankun子应用",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [32012, 32010, 32011],
      "cmdbSettings": "{\"silent\": false, \"webPort\": 8080, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"imageName\": \"\", \"innerSite\": false, \"isStateful\": false, \"observation\": false, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"healthCheckUri\": \"/payment-order-manage/healthcheck\", \"languageVersion\": \"14.15.0\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 8676,
      "name": "business-workbench",
      "description": "业务工作台",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [31502, 31503, 31504],
      "cmdbSettings": "{\"silent\": false, \"webPort\": 8080, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"imageName\": \"\", \"innerSite\": false, \"isStateful\": false, \"observation\": false, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"healthCheckUri\": \"/business-workbench/healthcheck\", \"languageVersion\": \"14.15.0\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 0,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 8611,
      "name": "settlement-platform-admin",
      "description": "结算运营台\nhttp://ops.test.ximalaya.com/gatekeeper/settlement-platform-admin/home",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [31145, 31147],
      "cmdbSettings": "{\"buildTool\":\"yarn\",\"innerSite\":false,\"language\":\"Javascript\",\"languageVersion\":\"16.14.0\",\"serviceTypes\":\"static-web\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 8539,
      "name": "add-credit-h5",
      "description": "喜点, 喜钻 充值 h5项目\nhttps://m.test.ximalaya.com/gatekeeper/add-credit-h5/addCredit/XISpot",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [27074, 35715, 27076],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"innerSite\": true, \"isStateful\": false, \"observation\": false, \"serviceTypes\": \"static-web\", \"languageVersion\": \"14.15.0\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 8406,
      "name": "transform-accounting-voucher",
      "description": "业财核算管理后台\n 业财http://ops.test.ximalaya.com/gatekeeper/transform-accounting-voucher\n\n业财transform-accounting-voucher子应用 财务详情 http://ops.test.ximalaya.com/gatekeeper/bizfinancial-info-admin/financialbudget/indexCenter\n财务会计核算工作台，提供收款、付款、收入、成本的会计凭证管理，以及业财转换规则配置能力",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [26375, 26376, 26377],
      "cmdbSettings": "{\"silent\": false, \"webPort\": 8080, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"imageName\": \"\", \"innerSite\": false, \"isStateful\": false, \"observation\": false, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"healthCheckUri\": \"/transform-accounting-voucher/healthcheck\", \"languageVersion\": \"14.15.0\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 8006,
      "name": "general-order-detail",
      "description": "通用订单详情",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [24447, 24448, 24449],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"innerSite\": false, \"observation\": false, \"serviceTypes\": \"static-web\", \"languageVersion\": \"14.15.0\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 0,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 7837,
      "name": "anchor-financial-admin",
      "description": "批量调账",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [23800, 23801, 23802],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"isStateful\": false, \"observation\": false, \"serviceTypes\": \"static-web\", \"languageVersion\": \"12.19.0\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 7708,
      "name": "newretail-mall-h5-spa",
      "description": "官方商城（迁移）",
      "gitExistProject": false,
      "ownerName": "陈寅",
      "pipelineIds": [23404, 23405, 23406],
      "cmdbSettings": "{\"silent\": false, \"webPort\": 8080, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"imageName\": \"\", \"isStateful\": false, \"observation\": false, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"healthCheckUri\": \"/newretail-mall-h5-spa/healthcheck\", \"languageVersion\": \"10.16.2\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 0,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 7590,
      "name": "hybrid-earning-v2",
      "description": "新收益中心 https://m.test.ximalaya.com/business-financial-account-mobile-web/home/view#/",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [23016, 23017, 23018],
      "cmdbSettings": "{\"buildTool\":\"yarn\",\"innerSite\":true,\"language\":\"Javascript\",\"languageVersion\":\"16.14.0\",\"serviceTypes\":\"static-web\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 7274,
      "name": "newretail-good-detail",
      "description": "新版商详页",
      "gitExistProject": false,
      "ownerName": "陈寅",
      "pipelineIds": [22038, 22039, 22040],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"innerSite\": true, \"observation\": false, \"serviceTypes\": \"static-web\", \"languageVersion\": \"14.15.0\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 0,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 6762,
      "name": "ops-shop-admin",
      "description": "电商中台，店铺管理 OPS 后台。\nhttp://ops.test.ximalaya.com/gatekeeper/ops-shop-admin/",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [20466, 20467, 20468],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"imageName\": \"\", \"isStateful\": false, \"observation\": false, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"languageVersion\": \"14.15.0\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 6759,
      "name": "common-payment-v3",
      "description": "结算页  h5 \nhttps://m.test.ximalaya.com/trade-v3/settlement/orderview?orderItems=%5B%7B%22itemId%22%3A%222039200001693168%22%2C%22quantity%22%3A%221%22%7D%2C%7B%22itemId%22%3A%222039200001693169%22%2C%22quantity%22%3A%221%22%7D%5D&usrContactId=1158455&usrContactId=11605390474",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [20458, 20459, 20460],
      "cmdbSettings": "{\"buildTool\":\"yarn\",\"innerSite\":true,\"language\":\"Javascript\",\"languageVersion\":\"14.15.0\",\"serviceTypes\":\"static-web\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 6657,
      "name": "voucher-list",
      "description": "我的代金券页面",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [20116, 20117, 20118],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"npm\", \"imageName\": \"\", \"isStateful\": false, \"observation\": false, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"languageVersion\": \"10.16.2\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 0,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 6626,
      "name": "ops-tax-management",
      "description": "报税管理后台",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [20016, 20017, 20018],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"imageName\": \"\", \"isStateful\": false, \"observation\": false, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"languageVersion\": \"14.15.0\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 0,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 6339,
      "name": "business-lib",
      "description": "商业化，公共类库。",
      "gitExistProject": false,
      "ownerName": "钱进",
      "pipelineIds": [19132, 19133, 19134],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"imageName\": \"\", \"isStateful\": false, \"observation\": false, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"languageVersion\": \"10.16.2\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 0,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 6148,
      "name": "shopping-cart-resource-allocation-web",
      "description": "购物车资源位配置\nhttps://ops.ximalaya.com/gatekeeper/shopping-cart-resource-allocation-web",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [18550, 18551, 18552],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"imageName\": \"\", \"isStateful\": false, \"observation\": false, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"languageVersion\": \"10.16.2\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 6107,
      "name": "signature-management-mobile-web",
      "description": "签约管理\nhttp://m.test.ximalaya.com/gatekeeper/signature-management-mobile-web",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [18416, 18417, 18418],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"imageName\": \"\", \"isStateful\": false, \"observation\": false, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"languageVersion\": \"10.16.2\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 6098,
      "name": "business-aggregate-admin-web",
      "description": "AGG 管理后台",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [18388, 18389, 18390],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"imageName\": \"\", \"isStateful\": false, \"observation\": false, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"languageVersion\": \"10.16.2\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 6094,
      "name": "ops-proportion-manage",
      "description": "ops分成比例管理系统",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [18374, 18375, 18376],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"imageName\": \"\", \"isStateful\": false, \"observation\": false, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"languageVersion\": \"10.16.2\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 0,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 6033,
      "name": "xi-an-manage",
      "description": "喜安综合服务平台",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [18191, 18192, 18193],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"imageName\": \"\", \"isStateful\": false, \"observation\": false, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"languageVersion\": \"10.16.2\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 0,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 5798,
      "name": "iap-order",
      "description": "苹果 iap 权益恢复\nhttps://static2.test.ximalaya.com/yx/iap-order/last/build/index.html",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [17527, 17528, 17529],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"imageName\": \"\", \"isStateful\": false, \"observation\": false, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"languageVersion\": \"10.16.2\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 5761,
      "name": "invoices-admin",
      "description": "发票服务后台http://ops.test.ximalaya.com/invoice-admin-web/sellerInfo/show;jsessionid=300891083E6F8F672497D61433DF726C",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [17409, 17410, 17411],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"npm\", \"imageName\": \"\", \"isStateful\": false, \"observation\": false, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"languageVersion\": \"8.11.1\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 5756,
      "name": "risk-audit-admin",
      "description": "风控审核，OPS 后台。",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [17394, 17395, 17396],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"imageName\": \"\", \"isStateful\": false, \"observation\": false, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"languageVersion\": \"10.16.2\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 0,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 5645,
      "name": "business-distribution-admin",
      "description": "电商中台，分销管理后台。",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [17045, 17046, 17047],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"imageName\": \"\", \"isStateful\": false, \"observation\": false, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"languageVersion\": \"10.16.2\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 0,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 5580,
      "name": "tap-order",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [16823, 16824, 16825],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"imageName\": \"\", \"isStateful\": false, \"observation\": false, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"languageVersion\": \"8.11.1\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 0,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 5521,
      "name": "frequently_asked_questions",
      "description": "充值常见问题h5\n\nhttps://mp.ximalaya.com/xmacc/help/index/ios\n\nhttps://mp.ximalaya.com/xmacc/help/index/android\n\n修改线上版本号 找交易 \n服务端应用\nxima-accounting-mobile-web",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [16581, 16582, 16583],
      "cmdbSettings": "{\"buildTool\":\"pnpm\",\"innerSite\":true,\"language\":\"Javascript\",\"languageVersion\":\"16.14.0\",\"serviceTypes\":\"static-web\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 5494,
      "name": "price-management",
      "description": "价格管理 \\n\nhttp://ops.test.ximalaya.com/business-price-center-admin/home;jsessionid=54EC40E54243CB76224D29A6E9423C91;jsessionid=8E8139743E16466C6636F41B93A958EF;jsessionid=33E434262664DC7B840B57D4EAC1590A;jsessionid=7044659BA2DCF0DD7CB2EBD48F617F92#/price/edit?id=100206",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [16497, 16498, 16499],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"npm\", \"imageName\": \"\", \"isStateful\": false, \"observation\": false, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"languageVersion\": \"10.16.2\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 5489,
      "name": "payment-details",
      "description": "提现详情http://ops.test.ximalaya.com/business-financial-admin-web/withdraw/check/detail;jsessionid=A0BF5DAB66BC4B6D511959495FE50F9F?merchantOrderNo=3032022081005710033277",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [16457, 16458, 16459],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"innerSite\": false, \"observation\": false, \"serviceTypes\": \"static-web\", \"languageVersion\": \"14.15.0\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 5318,
      "name": "user_tax_config",
      "description": "用户税务配置",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [15919, 15920, 15921],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"imageName\": \"\", \"isStateful\": false, \"observation\": false, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"languageVersion\": \"10.16.2\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 5252,
      "name": "iOS-top-up-helper",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [15720, 15721, 15722],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"imageName\": \"\", \"isStateful\": false, \"observation\": false, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"languageVersion\": \"8.11.1\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 0,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 5136,
      "name": "business-wallet",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [15374, 15375, 15376],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"npm\", \"imageName\": \"\", \"isStateful\": false, \"observation\": false, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"languageVersion\": \"10.16.2\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 0,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 5114,
      "name": "virtual-coin-service-protocol",
      "description": "喜钻充值服务协议 \nhttp://m.test.ximalaya.com/virtual-coin-service-protocol",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [15306, 15307, 15308],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"imageName\": \"\", \"isStateful\": false, \"observation\": false, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"languageVersion\": \"8.11.1\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 4792,
      "name": "finance-ocr-system",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [14341, 14342, 14343],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"isStateful\": false, \"observation\": false, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"languageVersion\": \"8.11.1\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 0,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 4781,
      "name": "budget-system",
      "description": "财务中台\n\nhttp://ops.test.ximalaya.com/finance-admin/index/report/bank-statements",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [14310, 14311, 14312],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"isStateful\": false, \"observation\": false, \"serviceTypes\": \"static-web\", \"languageVersion\": \"10.16.2\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 4744,
      "name": "finance-ocr-app",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [14200, 14201, 14202],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"isStateful\": false, \"observation\": false, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"languageVersion\": \"8.11.1\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 0,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 4711,
      "name": "ops-reconikiation-sys",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [14103, 14104, 14105],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"isStateful\": false, \"observation\": false, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"languageVersion\": \"8.11.1\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 0,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 4699,
      "name": "goods-shop-management",
      "description": "商家中心 https://pop.test.ximalaya.com/business-merchant-web/#/goods",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [14067, 14068, 14069],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"isStateful\": false, \"observation\": false, \"serviceTypes\": \"static-web\", \"languageVersion\": \"10.16.2\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 4423,
      "name": "activity-organization-anchor-leaderboard",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [13254, 13255, 13256],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"isStateful\": false, \"observation\": false, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"languageVersion\": \"8.11.1\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 0,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 4332,
      "name": "profit_admin",
      "description": "喜马拉雅收益中心提现后台\n云效 http://yunxiao.xmly.work/titan/appcenter/4332/overview\n\n原地址：http://ops.test.ximalaya.com/business-financial-admin-web/withdraw\n\n用户提现打款审核\n云效同上喜马拉雅收益中心提现后台\n\nhttp://ops.test.ximalaya.com/business-financial-admin-web/withdrawbill",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [12986, 12987, 12988],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"isStateful\": false, \"observation\": false, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"languageVersion\": \"8.11.1\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 4311,
      "name": "anchor-ecommerce",
      "description": "常用问题\nhttps://m.test.ximalaya.com/business-trade-material-aftersale-web/index/order/question",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [12922, 12923, 12924],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"innerSite\": false, \"isStateful\": false, \"observation\": false, \"serviceTypes\": \"static-web\", \"languageVersion\": \"12.19.0\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 4288,
      "name": "invoice",
      "description": "发票h5 地址: http://ops.test.ximalaya.com/invoice-mobile-web/invoice/v1",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [12851, 12852, 12853],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"isStateful\": false, \"observation\": false, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"languageVersion\": \"8.11.1\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 4182,
      "name": "trade-order-manage",
      "description": "交易管理后台http://ops.ximalaya.com/business-trade-admin-web/order/show;jsessionid=954D4FFFA9589286113A3804CD290BB0;jsessionid=7D1EC0C4849D5DBAADEF2F059D827677",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [12542, 12543, 12544],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"isStateful\": false, \"observation\": false, \"deployServer\": \"production\", \"serviceTypes\": \"static-web\", \"languageVersion\": \"8.11.1\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 1,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 3952,
      "name": "ops-whitelist",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [11864, 11865, 11866],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"npm\", \"isStateful\": false, \"observation\": false, \"serviceTypes\": \"static-web\", \"languageVersion\": \"10.16.2\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 0,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    },
    {
      "id": 3853,
      "name": "hybrid_cdkeys",
      "gitExistProject": false,
      "ownerName": "江浪",
      "pipelineIds": [11567, 11568, 11569],
      "cmdbSettings": "{\"silent\": false, \"language\": \"Javascript\", \"buildTool\": \"yarn\", \"isStateful\": false, \"observation\": false, \"serviceTypes\": \"static-web\", \"languageVersion\": \"8.11.1\"}",
      "serviceTypes": "static-web",
      "autoCreateDockerApp": false,
      "autoCreateXdcsApp": false,
      "autoCreateCMDBApp": false,
      "international": false,
      "classify": "server",
      "bundle": 0,
      "appCommonType": "common-app",
      "currentPage": 1,
      "pageSize": 10,
      "startIndex": 0
    }
  ]
}
