export const a = [
  {
    id: 3846,
    name: "bind-bank-card",
    description:
      "https://m.test.ximalaya.com/pay-membership-gateway-web/member/card/show/33182352364810768#/acc-list",
    gitExistProject: false,
    ownerName: "江浪",
    pipelineIds: [11546, 11547, 11548],
    cmdbSettings:
      '{"silent": false, "language": "Javascript", "buildTool": "npm", "isStateful": false, "observation": false, "serviceTypes": "static-web", "languageVersion": "10.16.2"}',
    serviceTypes: "static-web",
    autoCreateDockerApp: false,
    autoCreateXdcsApp: false,
    autoCreateCMDBApp: false,
    international: false,
    classify: "server",
    bundle: 1,
    appCommonType: "common-app",
    currentPage: 1,
    pageSize: 10,
    startIndex: 0,
  },
  {
    id: 3528,
    name: "coupon-list",
    description:
      "优惠券列表 https://m.test.ximalaya.com/promotion/coupon/user/index/list",
    gitExistProject: false,
    ownerName: "江浪",
    pipelineIds: [10612, 10611],
    cmdbSettings:
      '{"silent": false, "language": "Javascript", "buildTool": "npm", "isStateful": false, "observation": false, "serviceTypes": "static-web", "languageVersion": "10.16.2"}',
    serviceTypes: "static-web",
    autoCreateDockerApp: false,
    autoCreateXdcsApp: false,
    autoCreateCMDBApp: false,
    international: false,
    classify: "server",
    bundle: 1,
    appCommonType: "common-app",
    currentPage: 1,
    pageSize: 10,
    startIndex: 0,
  },
  {
    id: 3462,
    name: "inner-project-display",
    gitExistProject: false,
    ownerName: "江浪",
    pipelineIds: [10424, 10425, 10426],
    cmdbSettings:
      '{"silent": false, "language": "Javascript", "buildTool": "yarn", "isStateful": false, "observation": false, "serviceTypes": "static-web", "languageVersion": "10.16.2"}',
    serviceTypes: "static-web",
    autoCreateDockerApp: false,
    autoCreateXdcsApp: false,
    autoCreateCMDBApp: false,
    international: false,
    classify: "server",
    bundle: 0,
    appCommonType: "common-app",
    currentPage: 1,
    pageSize: 10,
    startIndex: 0,
  },
  {
    id: 3236,
    name: "pay-order",
    gitExistProject: false,
    ownerName: "江浪",
    pipelineIds: [9755, 9756, 9757],
    cmdbSettings:
      '{"silent": false, "language": "Javascript", "buildTool": "npm", "isStateful": false, "observation": false, "serviceTypes": "static-web", "languageVersion": "10.16.2"}',
    serviceTypes: "static-web",
    autoCreateDockerApp: false,
    autoCreateXdcsApp: false,
    autoCreateCMDBApp: false,
    international: false,
    classify: "server",
    bundle: 0,
    appCommonType: "common-app",
    currentPage: 1,
    pageSize: 10,
    startIndex: 0,
  },
  {
    id: 3094,
    name: "address-service-front",
    description:
      "https://m.test.ximalaya.com/contact/addressPlugin?returnUrl=http%3A%2F%2Fm.test.ximalaya.com%2Ftrade-v3%2Fsettlement%2Forderview%3ForderItems%3D%255B%257B%2522itemId%2522%253A%25222040600006345609%2522%252C%2522quantity%2522%253A%25221%2522%252C%2522extension%2522%253A%257B%2522sourceType%2522%253A26%252C%2522sourceValue%2522%253A%2522%257B%255C%2522i%255C%2522%253A%255C%25223%255C%2522%252C%255C%2522a%255C%2522%253A%255C%25220_0_0_334177%255C%2522%257D%2522%257D%257D%255D",
    gitExistProject: false,
    ownerName: "江浪",
    pipelineIds: [9338, 9339, 9340],
    cmdbSettings:
      '{"silent": false, "language": "Javascript", "buildTool": "yarn", "isStateful": false, "observation": false, "serviceTypes": "static-web", "languageVersion": "10.16.2"}',
    serviceTypes: "static-web",
    autoCreateDockerApp: false,
    autoCreateXdcsApp: false,
    autoCreateCMDBApp: false,
    international: false,
    classify: "server",
    bundle: 1,
    appCommonType: "common-app",
    currentPage: 1,
    pageSize: 10,
    startIndex: 0,
  },
  {
    id: 3019,
    name: "business-content-list",
    gitExistProject: false,
    ownerName: "江浪",
    pipelineIds: [9111, 9112, 9113],
    cmdbSettings:
      '{"silent": false, "language": "Javascript", "buildTool": "yarn", "isStateful": false, "observation": false, "serviceTypes": "static-web", "languageVersion": "10.16.2"}',
    serviceTypes: "static-web",
    autoCreateDockerApp: false,
    autoCreateXdcsApp: false,
    autoCreateCMDBApp: false,
    international: false,
    classify: "server",
    bundle: 0,
    appCommonType: "common-app",
    currentPage: 1,
    pageSize: 10,
    startIndex: 0,
  },
  {
    id: 2966,
    name: "my-order-h5",
    description: "http://m.test.ximalaya.com/trade/order/index/order-list",
    gitExistProject: false,
    ownerName: "江浪",
    pipelineIds: [8954, 8955, 8956],
    cmdbSettings:
      '{"buildTool":"yarn","innerSite":true,"language":"Javascript","languageVersion":"14.15.0","serviceTypes":"static-web"}',
    serviceTypes: "static-web",
    autoCreateDockerApp: false,
    autoCreateXdcsApp: false,
    autoCreateCMDBApp: false,
    international: false,
    classify: "server",
    bundle: 1,
    appCommonType: "common-app",
    currentPage: 1,
    pageSize: 10,
    startIndex: 0,
  },
  {
    id: 2783,
    name: "hybrid_earning",
    description:
      "收益中心c端结果 只能站内打开\nhttps://e.test.ximalaya.com/withdrawflow/user/1283945/orderno/3032022062905710104255?uid=1283945&accType=2&app=iting&version=9.0.42.9604",
    gitExistProject: false,
    ownerName: "江浪",
    pipelineIds: [8414, 8415, 8416],
    cmdbSettings:
      '{"silent": false, "language": "Javascript", "buildTool": "yarn", "isStateful": false, "observation": false, "serviceTypes": "static-web", "languageVersion": "10.16.2"}',
    serviceTypes: "static-web",
    autoCreateDockerApp: false,
    autoCreateXdcsApp: false,
    autoCreateCMDBApp: false,
    international: false,
    classify: "server",
    bundle: 1,
    appCommonType: "common-app",
    currentPage: 1,
    pageSize: 10,
    startIndex: 0,
  },
  {
    id: 2717,
    name: "account-freeze-statistics",
    description:
      "主播账号冻结记录\nhttp://ops.test.ximalaya.com/business-financial-admin-web/withdrawaccount/frozen/record",
    gitExistProject: false,
    ownerName: "江浪",
    pipelineIds: [8213, 8214, 8215],
    cmdbSettings:
      '{"silent": false, "language": "Javascript", "buildTool": "npm", "isStateful": false, "observation": false, "serviceTypes": "static-web", "languageVersion": "8.11.1"}',
    serviceTypes: "static-web",
    autoCreateDockerApp: false,
    autoCreateXdcsApp: false,
    autoCreateCMDBApp: false,
    international: false,
    classify: "server",
    bundle: 1,
    appCommonType: "common-app",
    currentPage: 1,
    pageSize: 10,
    startIndex: 0,
  },
  {
    id: 2680,
    name: "ops-order-manage",
    description:
      "实物商品订单管理 \nhttp://ops.test.ximalaya.com/business-trade-admin-web/shipOrder/show",
    gitExistProject: false,
    ownerName: "江浪",
    pipelineIds: [8099, 8101],
    cmdbSettings:
      '{"silent": false, "language": "Javascript", "buildTool": "yarn", "innerSite": false, "observation": false, "serviceTypes": "static-web", "languageVersion": "14.15.0"}',
    serviceTypes: "static-web",
    autoCreateDockerApp: false,
    autoCreateXdcsApp: false,
    autoCreateCMDBApp: false,
    international: false,
    classify: "server",
    bundle: 1,
    appCommonType: "common-app",
    currentPage: 1,
    pageSize: 10,
    startIndex: 0,
  },
  {
    id: 2651,
    name: "goods-management",
    description:
      "项目地址 http://ops.test.ximalaya.com/business-product-category-admin-web/home;jsessionid=AB036FA858837B4BC6ADE924E676D7AC#/",
    gitExistProject: false,
    ownerName: "江浪",
    pipelineIds: [8013, 8014, 8015],
    cmdbSettings:
      '{"silent": false, "language": "Javascript", "buildTool": "npm", "isStateful": false, "observation": false, "serviceTypes": "static-web", "languageVersion": "10.16.2"}',
    serviceTypes: "static-web",
    autoCreateDockerApp: false,
    autoCreateXdcsApp: false,
    autoCreateCMDBApp: false,
    international: false,
    classify: "server",
    bundle: 1,
    appCommonType: "common-app",
    currentPage: 1,
    pageSize: 10,
    startIndex: 0,
  },
  {
    id: 2219,
    name: "listen-list",
    gitExistProject: false,
    ownerName: "江浪",
    pipelineIds: [6714, 6715, 6716],
    cmdbSettings:
      '{"silent": false, "language": "Javascript", "buildTool": "npm", "isStateful": false, "observation": false, "serviceTypes": "static-web", "languageVersion": "10.16.2"}',
    serviceTypes: "static-web",
    autoCreateDockerApp: false,
    autoCreateXdcsApp: false,
    autoCreateCMDBApp: false,
    international: false,
    classify: "server",
    bundle: 0,
    appCommonType: "common-app",
    currentPage: 1,
    pageSize: 10,
    startIndex: 0,
  },
  {
    id: 1698,
    name: "promotion-management",
    description:
      "营销后台\nhttp://ops.test.ximalaya.com/business-promotion-admin-web/home#/management",
    gitExistProject: false,
    ownerName: "江浪",
    pipelineIds: [5120, 5121, 5122],
    cmdbSettings:
      '{"silent": false, "language": "Javascript", "buildTool": "yarn", "innerSite": false, "observation": false, "serviceTypes": "static-web", "languageVersion": "14.15.0"}',
    serviceTypes: "static-web",
    autoCreateDockerApp: false,
    autoCreateXdcsApp: false,
    autoCreateCMDBApp: false,
    international: false,
    classify: "server",
    bundle: 1,
    appCommonType: "common-app",
    currentPage: 1,
    pageSize: 10,
    startIndex: 0,
  },
  {
    id: 1488,
    name: "checkstand",
    description:
      "h5收银台\n\n免息 ->  https://m.test.ximalaya.com/pay-cashier-gateway-web/cashier/placeorder?client=H5&device=ANDROID&bizTypeId=201&amount=100 \n不免息 ->  https://m.test.ximalaya.com/pay-cashier-gateway-web/cashier/placeorder?client=H5&device=ANDROID&bizTypeId=202&amount=100 ",
    gitExistProject: false,
    ownerName: "江浪",
    pipelineIds: [4476, 4477, 4478],
    cmdbSettings:
      '{"silent": false, "language": "Javascript", "buildTool": "npm", "isStateful": false, "observation": false, "serviceTypes": "static-web", "languageVersion": "10.16.2"}',
    serviceTypes: "static-web",
    autoCreateDockerApp: false,
    autoCreateXdcsApp: false,
    autoCreateCMDBApp: false,
    international: false,
    classify: "server",
    bundle: 1,
    appCommonType: "common-app",
    currentPage: 1,
    pageSize: 10,
    startIndex: 0,
  },
  {
    id: 1487,
    name: "common-payment-result",
    gitExistProject: false,
    ownerName: "江浪",
    pipelineIds: [4473, 4474, 4475],
    cmdbSettings:
      '{"silent": false, "language": "Javascript", "buildTool": "npm", "isStateful": false, "observation": false, "serviceTypes": "static-web", "languageVersion": "10.16.2"}',
    serviceTypes: "static-web",
    autoCreateDockerApp: false,
    autoCreateXdcsApp: false,
    autoCreateCMDBApp: false,
    international: false,
    classify: "server",
    bundle: 0,
    appCommonType: "common-app",
    currentPage: 1,
    pageSize: 10,
    startIndex: 0,
  },
  {
    id: 1485,
    name: "common-payment",
    gitExistProject: false,
    ownerName: "江浪",
    pipelineIds: [4467, 4468, 4469],
    cmdbSettings:
      '{"silent": false, "language": "Javascript", "buildTool": "npm", "isStateful": false, "observation": false, "serviceTypes": "static-web", "languageVersion": "10.16.2"}',
    serviceTypes: "static-web",
    autoCreateDockerApp: false,
    autoCreateXdcsApp: false,
    autoCreateCMDBApp: false,
    international: false,
    classify: "server",
    bundle: 0,
    appCommonType: "common-app",
    currentPage: 1,
    pageSize: 10,
    startIndex: 0,
  },
  {
    id: 1458,
    name: "my-earning",
    description:
      "http://m.test.ximalaya.com/business-accounting-web/accounting/page/billdownload",
    gitExistProject: false,
    ownerName: "江浪",
    pipelineIds: [4386, 4387, 4388],
    cmdbSettings:
      '{"silent": false, "language": "Javascript", "buildTool": "yarn", "isStateful": false, "observation": false, "serviceTypes": "static-web", "languageVersion": "10.16.2"}',
    serviceTypes: "static-web",
    autoCreateDockerApp: false,
    autoCreateXdcsApp: false,
    autoCreateCMDBApp: false,
    international: false,
    classify: "server",
    bundle: 1,
    appCommonType: "common-app",
    currentPage: 1,
    pageSize: 10,
    startIndex: 0,
  },
  {
    id: 1173,
    name: "business-subscription-schedule-admin-web",
    gitExistProject: false,
    ownerName: "庞克臣",
    pipelineIds: [68696, 33874, 61589],
    cmdbSettings:
      '{"buildTool":"maven","defaultMaxSurge":100,"isStateful":false,"language":"Java","languageVersion":"jdk8","minReady":120,"namespace":"dszt-pay","namespaceDesc":"支付平台@电商中台","observation":false,"packageType":2,"serviceTypes":"web","silent":false,"webPort":8080}',
    serviceTypes: "web",
    autoCreateDockerApp: false,
    autoCreateXdcsApp: false,
    autoCreateCMDBApp: false,
    international: false,
    classify: "server",
    bundle: 1,
    appCommonType: "common-app",
    currentPage: 1,
    pageSize: 10,
    startIndex: 0,
  },
];
